### ISSUE TITLE
Add some wysiwyg editor in the Description field

### ISSUE THREAD

**Issue by luanfonceca** [luanfonceca/speakerfight#1]
We need to use some kind of wysiwyg editor in the description field of Proposal/Event Model.
One of our options is the [Medium Editor](https://github.com/daviferreira/medium-editor)

* The conversion of code to html is already being done by the template.

**Comment by cacarrara** [comment]
Hey @luanfonceca, maybe we should close this issue now. ;)

**Comment by luanfonceca** [comment]
Yes we should :D
