### ISSUE TITLE
Increase the left navbar width

### ISSUE THREAD

**Issue by luanfonceca** [luanfonceca/speakerfight#102]
![screen shot 2015-09-18 at 8 16 49 pm](https://cloud.githubusercontent.com/assets/1490875/9972994/3e544b0e-5e42-11e5-8011-1909d1dda453.png)

**Comment by Vinihcampos** [comment]
Vou ficar com essa issue.

**Comment by jonatasoliveira** [comment]
The pull request #112 should fix this issue.
