### ISSUE TITLE
Add Export Event feature in the Site

### ISSUE THREAD

**Issue by luanfonceca** [luanfonceca/speakerfight#104]
We need to take a print of the Export Event button: http://127.0.0.1:8000/events/rupy-natal/, we need to create some simple text to explain it.

| ID | Title | Author | Author E-Mail | Vote Rate | Votes Count |
| --- | --- | --- | --- | --- | --- |
| 3 | Django Vanilla Views | admin | admin@speakerfight.com |  | 0 |
| 2 | Flask is Fun | admin | admin@speakerfight.com |  | 0 |
| 1 | Generating code documentation in Python | admin | admin@speakerfight.com |  | 0 |

**Comment by mauricioabreu** [comment]
By "export" you mean CSV file, right?

**Comment by mauricioabreu** [comment]
@luanfonceca

**Comment by luanfonceca** [comment]
This issue has almost two years haha

And its not even in a milestone. So on #224 this should be better covered, if we do something today it just be a waste of time.

<3
