### ISSUE TITLE
Translate Event jury text in site

### ISSUE THREAD

**Issue by luanfonceca** [luanfonceca/speakerfight#115]
Right now the "Event Jury" feature text is not tanslated to portuguese.

![screen shot 2015-10-05 at 3 05 43 pm](https://cloud.githubusercontent.com/assets/1490875/10289041/b362f624-6b72-11e5-9b7c-3cc64916a30f.png)

**Comment by julioeiras** [comment]
I take this one ;)

**Comment by luanfonceca** [comment]
Thanks @julioeiras, in fact the message is wrong too haha
I think something like: "The event jury restricts the vote to a group of users. Anyone outside of that group will just see the proposals and they cannot vote."

Can you change the text and translate it?

o/

**Comment by julioeiras** [comment]
Sure I can! I couldn't  find how to change the language, any tips?

**Comment by luanfonceca** [comment]
You can add `LANGUAGE_CODE = 'pt_BR'` on your `local_settings.py` file. 

There isn`t a feature to change the language in the plataform, yet. There is a open issue for that #9.

**Comment by julioeiras** [comment]
Oh, ok, I just wanted to check if there was a way other then in the settings. Thanks!

**Comment by luanfonceca** [comment]
Thanks for that @julioeiras, as you can see it is merged and deployed.

http://speakerfight.com/
![screen shot 2015-10-17 at 2 18 57 pm](https://cloud.githubusercontent.com/assets/1490875/10560218/1a5e6bfe-74da-11e5-9dc8-5550df920fa5.png)

**Comment by julioeiras** [comment]
Thanks a lot! :D

Julio Cesar Eiras Melanda
-------------------------------------------------------------------------------------
Universidade Federal de São Paulo
Mestrando em Ciência da Computação

Universidade Federal de Itajubá
Bacharel em Ciência da Computação
-------------------------------------------------------------------------------------
Skype: jcemelanda
cel/whatsapp: (012) 99150-7808
-------------------------------------------------------------------------------------
blog: http://programeempython.com.br <http://programeempython.blog.br>
github: https://github.com/julioeiras
slideshare: http://www.slideshare.net/jcemelanda
-------------------------------------------------------------------------------------
twitter: @jcemelanda
-------------------------------------------------------------------------------------
Linux user: #498290
Fedora User
[image: icone: Facebook] <https://www.facebook.com/jcemelanda>  [image:
icone: Linkedin] <http://www.linkedin.com/in/jcemelanda>  [image: icone:
Twitter] <https://twitter.com/jcemelanda>  [image: icone: Google+]
<https://plus.google.com/103969569904784103570/posts>

2015-10-17 14:19 GMT-03:00 Luan Fonseca <notifications@github.com>:
