### ISSUE TITLE
Add PEP8 to #coding-rules in CONTRIBUTING.md

### ISSUE THREAD

**Issue by luanfonceca** [luanfonceca/speakerfight#123]
We need to tell people to use the PEP8 standards for coding, like the max length of chars in a line. Two spaces after classes, one after functions... all that kind of things.

This is highly needed for non-python programmers, because we have a strong culture in code quality.

https://github.com/luanfonceca/speakerfight/blob/master/CONTRIBUTING.md#coding-rules

**Comment by mauricioabreu** [comment]
I think that is enough to link the pep8 documentation. Duplicating information is not a good thing in this case because the Python documentation is clear and concise.
What is your opinion?

**Comment by luanfonceca** [comment]
I dont know, i think really annoying a python code that doesn't follow at least the PEP8, like wrong spaces, new lines, naming classes... And if we had a *coding rules* we can argue with the people with more sure and we can show examples from the `CONTRIBUTING.MD` itself

**Comment by mauricioabreu** [comment]
I know. It annoys me too but I don't think we need to show examples. PEP8 is a good and comprehensive document. We can do less work by just linking PEP8 document and telling users to install flake8 and run it before creating a pull request. Anyways, I am ok about showing some examples.

**Comment by vmesel** [comment]
@luanfonceca you should make the user test the code first during the Pull Request, so we could get an accurate fix!

**Comment by vmesel** [comment]
I think PEP8 coding rules should be followed, except for the char limit on a line! We do not have old computers that can't support more than 70 chars in a line(if you do have, ask for a new one in christmas).

**Comment by mauricioabreu** [comment]
It is not about computer screen size. It is about readability. :)
And it is not 70 characters, it is 79.

**Comment by vmesel** [comment]
@mauricioabreu is there anyway to get in touch with you? need to talk things about speaker fight! we could create a whatsapp/telegram group for the developers!

**Comment by mauricioabreu** [comment]
SpeakerFight has a gitter room. Let's talk about the project there. It is easier. :)

**Comment by luanfonceca** [comment]
I am closing this issue ok? I will not pass PRs with PEP8 problems, its so common to Python develoipers to code based on pep8 linters, so everyone usually are ok with it.
