### ISSUE TITLE
See my events

### ISSUE THREAD

**Issue by luanfonceca** [luanfonceca/speakerfight#124]
There should be nice for us to have a menu option, to show a list of events that i am the author. Like we have in "My proposals". With the same layout of the Events page.

**Comment by gtsalles** [comment]
Hey @luanfonceca I think I can do this :)
I'll talk to you on gitter when I'll do it ok?

**Comment by luanfonceca** [comment]
Can you get another one @gtsalles, this issue will be used for a software maintenance course in my university by @hugoandregg :(

**Comment by gtsalles** [comment]
Sure, no problem :)

**Comment by luanfonceca** [comment]
Closing this with the PR #125
