### ISSUE TITLE
Explain the voting criteria

### ISSUE THREAD

**Issue by luanfonceca** [luanfonceca/speakerfight#126]
For people who are migrating from callforpaperz, our process is a bit confusing, that should be nice if we create a simple doc explain how this works.

**Comment by deboraazevedo** [comment]
Is it really necessary? You have all the explanation about the voting in the "about" page. Do you want to have this explanation in English?

**Comment by luanfonceca** [comment]
We dont need this anymore, i will close it o/

All the Speakerfight é written in english and the language is set to `pt_BR` in the server because we dont closed the issue #9 yet.
