### ISSUE TITLE
Exclude the events with a due date of more than 4 months

### ISSUE THREAD

**Issue by luanfonceca** [luanfonceca/speakerfight#128]
Today we show all the events in the http://speakerfight.com/events, that should be nice if we hide from this page the events with the due date in more than 4 months. The events will still exist but we will not be showed in the `/events/`.

**Comment by jonatasoliveira** [comment]
@luanfonceca what do you think about only show events that will happen, in other words hide all the events that already have passed.

Maybe it's a good idea to have a page with all events and a nice call to action button to create a new event.

**Comment by mauricioabreu** [comment]
I agree with @jonatasoliveira 

/events is a good endpoint to show only upcoming events.
/events/most_recent or an endpoint with a query filter could be more appropriate to events that already happened.

**Comment by luanfonceca** [comment]
I agree with you @jonatasoliveira, but we can keep the `/events` with the upcoming and create a `/past_events` to show the others.

What about that?!

**Comment by mauricioabreu** [comment]
@luanfonceca yeah, much better than mine option hahahaha I suck at naming things.

**Comment by renatooliveira** [comment]
We discussed and maybe hide, not exclude,  the events would be better. Speakerfight wants to solve talks for events, and wants to take records. So I'm closing this issue to create new ones

- Only shows active events (Hide events after call for papers is closed).
- Create an area of past events

**Comment by vmesel** [comment]
@renatooliveira It should be better if we have another link to show the past event info and, maybe, make a survey for getting the user's satisfaction!
