### ISSUE TITLE
Upgrade to Django 1.9

### ISSUE THREAD

**Issue by mauricioabreu** [luanfonceca/speakerfight#129]
Django 1.9 was released (couple of months ago I think) and it would be good to support it.
I am already doing this here https://github.com/mauricioabreu/speakerfight/tree/upgrade-django-version

**Comment by mauricioabreu** [comment]
Some libraries to be aware of necessary changes in order to support Django 1.9 here:

django-queryset-csv:
https://github.com/azavea/django-queryset-csv/issues/78
https://github.com/azavea/django-queryset-csv/pull/82

django-activelink:
https://github.com/j4mie/django-activelink/issues/4

**Comment by mauricioabreu** [comment]
I made some code yesterday to Django 1.9 for activelink but it is not too easy.
The project itself has the test suite running on Django 1.3

**Comment by mauricioabreu** [comment]
Here is my pull request for django-activelink: https://github.com/j4mie/django-activelink/pull/6

**Comment by luanfonceca** [comment]
I am closing this issue based on that we already upgraded to the Django tip on the PR #157
