### ISSUE TITLE
Create Organizations

### ISSUE THREAD

**Issue by luanfonceca** [luanfonceca/speakerfight#130]
When i see an event created by @erichideki, at the end of the description he always adds some information and links about the Grupy-sp and Python Brasil, like:

http://speakerfight.com/events/aprendendo-python-janeiro-2016/

```
...

Informações Grupy-SP 

Github - https://github.com/grupy-sp/encontros  
Facebook - https://www.facebook.com/grupysp  
Twitter - https://twitter.com/grupysp  
Slack - https://grupysp.herokuapp.com  
Google Groups - https://groups.google.com/forum/#!forum/grupy-sp

Python Brasil

Facebook - https://www.facebook.com/pythonbrasil  
Twitter - https://twitter.com/pythonbrasil  
Google Groups - https://groups.google.com/forum/#!forum/python-brasil

Contatos

Eric Hideki - eric8197@gmail.com 
```
That should be in an "Organization", with Eric as a `member`.

The following mock is to help the development of this issue. This issue is just about the creation process of a Organization, **this needs to implement the changes and create files only for the create action of a Organization with only Name and About fields**, we will create issues for the rest of the actions and link it in here.

![screen shot 2017-10-03 at 18 45 24](https://user-images.githubusercontent.com/1490875/31150709-0d75aee0-a86b-11e7-81e0-4aefdca11639.png)

**Comment by mauricioabreu** [comment]
I am doing this one. It will be real fast. :+1:

**Comment by mauricioabreu** [comment]
Done.
