### ISSUE TITLE
Speaker Fight 19x uma palestra

### ISSUE THREAD

**Issue by vmesel** [luanfonceca/speakerfight#136]
Como se pode ver neste evento, o speaker fight duplicou as palestras do Régis!

http://speakerfight.com/events/encontro-de-abril-tudo-junto-e-misturado/

**Comment by luanfonceca** [comment]
Fala @vmesel, não é nem que ele tenha duplicado é que ta dando um problema no smtp e ele "trava" a plataforma depois de submeter (na hora de enviar o email notificando o autor do evento, jurí e o próprio participante).

Passei a tarde inteiro tentando corrigir isso mas não rolou, então vou desabilitar as notificações por email e tudo vai funcionar.

Valeu por notar o comportamento o/

**Comment by vmesel** [comment]
Muito obrigado @luanfonceca se você poder remover as duplicatas da palestra também eu agradeço!

**Comment by luanfonceca** [comment]
Removi já o/

**Comment by luanfonceca** [comment]
Tudo resolvido, já ta mandando email

o/
