### ISSUE TITLE
Improvements for Speaker Fight

### ISSUE THREAD

**Issue by vmesel** [luanfonceca/speakerfight#137]
Guys, what you think that should be improved in speaker fight, so I could work on? I want to be useful as any developer wants to!

**Comment by luanfonceca** [comment]
Hey @vmesel, here in the speakerfight we have a lots of awesome things to do, tell me what do you like most, something like, frontend, backend, create features, fix bugs, review code, tests?

And you can always do whatever you want to do in order to make the speakerfight better :D
