### ISSUE TITLE
Allow to change the vote

### ISSUE THREAD

**Issue by wagnerluis1982** [luanfonceca/speakerfight#138]
Once I vote on a speech I can't change my vote. If I vote by mistake, for instance, this makes a problem.

So, I think the user should be allowed to change his/her vote.

**Comment by luanfonceca** [comment]
Hey @wagnerluis1982 

Thats a dupe from the issue #91, if you want to help us to make a better project and fix that we will be really happy \o/

I am closing this one, i recommend you to join the conversation on the other issue :D

**Comment by wagnerluis1982** [comment]
Oh sorry, I did a brief search before I opened this one but I didn't note that.

For sure I'm going to join it.
