### ISSUE TITLE
Collapse big proposal descriptions

### ISSUE THREAD

**Issue by wagnerluis1982** [luanfonceca/speakerfight#140]
It would be good if the proposal descriptions were collapsed to reduce the scroll over the registered proposals.

A good baseline would be to collapse if description has more than two paragraphs.

**Comment by luanfonceca** [comment]
This is a nice and simple issue to be fixed who will impacto in a good way in all events, do you have interest on doing this? I can follow you through the steps needed to doit, if you want.

o/

**Comment by wagnerluis1982** [comment]
Well, it's a longtime since I wrote something for a webapp code, but I think I can handle this.

What frameworks are used for CSS and JS? According to what I saw in the source, it's bootstrap and jquery (because bootstrap), that's correct?

**Comment by luanfonceca** [comment]
Yep, Bootstrap, jquery and a bootstrap based theme.

**Comment by wagnerluis1982** [comment]
Ok, I'm going to check if I can make it. I'll keep you informed about progresses here!

**Comment by wagnerluis1982** [comment]
After a while I had some time to work at this issue :smile: 

I digged up the web for solutions to this subject but all I found uses some technique of rewrite the HTML to collapse/expand the text.

So I decided to write a code using the least JavaScript possible. I ended up in the following solution:

1. After page loads, I look at every `.proposal-description` and check if its height is greater than 150px, setting the height to 150px if it is. The following image show how is rendered on Google Chrome. Note in the collapsed area that the bottom has some opacity to show that the text was collapsed.

  ![collapsed](https://cloud.githubusercontent.com/assets/428341/19210385/f8eaa82a-8cf7-11e6-9606-d9f8f1d7c085.jpg)

2. The collapsed area is clickable (`cursor: pointer`), so when someone clicks, it expands.

## Comments

- With this solution, JavaScript is loaded only when the page loads and when the collapsed area is clicked: there is no event trigger.
- After the long text is expanded, it can't be collapsed again (unless the page is reloaded).
- I used 150px for height because looked good for me. 
- Other ways to show that the text is collapsed:
    - Change the background color of the area to some light yellow or green or something.
    - Add a `div` between the description and vote areas with the text "Show more". That was my first idea, but I didn't do it because would introduce a new i18n string.

What do you think?

Here the patch: [collapse-proposal.txt](https://github.com/luanfonceca/speakerfight/files/517430/collapse-proposal.txt)

**Comment by luanfonceca** [comment]
You should make a pull request instead of this patch, with a patch your
contribution will not be credited to you o/

Em sáb, 8 de out de 2016 01:59, Wagner Macedo <notifications@github.com>
escreveu:

**Comment by wagnerluis1982** [comment]
Oh, of course. I wanted to discuss here before I make the PR.

But you are right, I'll do it and move the discussion to there.

**Comment by luanfonceca** [comment]
Thanks, we cab discuss and review it on the PR o/

Em sáb, 8 de out de 2016 13:58, Wagner Macedo <notifications@github.com>
escreveu:
