### ISSUE TITLE
[Bug?] - Recent events as PythonBrasil[12] don't appear on list

### ISSUE THREAD

**Issue by nielsonsantana** [luanfonceca/speakerfight#143]
Só vi eventos listados até o mês de abril de 2016,
por outro lado o evento da PythonBrasil12(publicado no dia 9 de Junho de 2016) não foi listado.
Talvez tenha a ver com a não remoção dos eventos passados.

**Comment by mauricioabreu** [comment]
Mas eu achei aqui sim: http://speakerfight.com/events/

Porém a ordem pode confundir. Tô com um pouco de preguiça pra olhar a ordem no fonte, mas eu creio que não está por data de criação. :)

**Comment by nielsonsantana** [comment]
Oi @mauricioabreu.
O que você encontrou foi esse:
[PythonBrasil[11] - Tutoriais - Criado por R Nuccitelli em 26 de Agosto de 2015 às 15:08]
(http://speakerfight.com/events/pythonbrasil11-tutoriais/)

O que estou falando é esse:
[Python Brasil[12] - Apresentações - Criado por Eventos Python em 9 de Junho de 2016 às 00:18.] 
(http://speakerfight.com/events/python-brasil12-apresentacoes)

**Comment by mauricioabreu** [comment]
Não, o que eu vi foi o http://speakerfight.com/events/python-brasil12-apresentacoes/ mesmo
Entra em events e usa a busca do seu navegador. :)

**Comment by nielsonsantana** [comment]
É, Python Brasil[12] está na listagem. Pesquisei por "pythonbrasil" junto por isso que só mostrava a edição 11. Certamente a ordenação por data poderia ajudar bastante. Não faz sentido eventos antigos estarem no topo, a menos que a ordenação esteja sendo pelo nome.
