### ISSUE TITLE
Server Internal Error when acessing an event to which I send a proposal

### ISSUE THREAD

**Issue by julianaklulo** [luanfonceca/speakerfight#144]
I send a proposal to the event Python Brasil[12] - Apresentações, but when I'm logged in I can't access the event page. If I access the page without being logged, everything is normal, but when I log in to vote I get 'Server Internal Error' page. I tried in several browsers, and the error appears everywhere.

**Comment by mauricioabreu** [comment]
We are sorry for this. :(
I will investigate this problem. Ping me if you need more help.

**Comment by vmesel** [comment]
Is this issue solved?

**Comment by mauricioabreu** [comment]
@vmesel I don't know. But we have a huge problem here: Speakerfight lacks of a simple alarm system.
We don't know what happened because it is inside a log, a big text file.

We could use something like Sentry to intercept and log tracebacks.

**Comment by vmesel** [comment]
@mauricioabreu can you join me on gitter so we can try to solve this problem? We will need to contact @julianaklulo to see what she was doing that made this problem appear.

What Sentry does?

**Comment by mauricioabreu** [comment]
@vmesel it monitors and log tracebacks. It is easier than asking users "what happened" or "reading a huge log file". :)

**Comment by luanfonceca** [comment]
Hello folks, i will lot into that right now. o/

@mauricioabreu in fact we have a Sentry setup and it is working https://sentry.io/speakerfight/speakerfight/

But as i was busy for a while we have a lots of events not resolved in there.
