### ISSUE TITLE
Convert css to sass to be more productive

### ISSUE THREAD

**Issue by joseluizcoe** [luanfonceca/speakerfight#150]
Why we need this?
Let's see one example: The file "flat-icons.css" is about vote area icons. This file provide icons in svg format, but only one size. Everytime i change the size of svg background, all position/configuration must to be changed too. I'd like to use the same icons on small, medium and large size without copy/paste code. I think issue #35 is not similar because talk about resolve only this case. A lot of other css files could be more simple to maintain if we use some preprocessor (such as less or sass).

**Comment by vmesel** [comment]
The icons should be improved or the SASS should be done! The issue title and description are totally different subjects.

**Comment by joseluizcoe** [comment]
Hi, @vmesel. This issue is about convert css to sass (see the title). If convert css to sass, problems like #35 could be resolved fast. The description about icons it's just one example.

**Comment by luanfonceca** [comment]
I am closing this issue. For now our stylecheet has less than 200 lines and our theme is based on a free bootstrap theme who doesnt offer a sass version.

For us to implement this in the deploy fabric and will add a bigger learning curve for people to contribute with Speakerfight.

If someday we think on a full redesign of our platform we probably should use some css compressor.

o/
