### ISSUE TITLE
Change e-mail sender from "Noreply" to "Speakerfight - Noreply" (or similar)

### ISSUE THREAD

**Issue by joseluizcoe** [luanfonceca/speakerfight#152]
I forgot my password and ask to speakerfight for a new one. When i received email, gmail show me the sender name as "noreply". I think the name could something like "Speakerfight (noreply)" just to be easy to find. See examples bellow:

# Gmail
![captura de tela 2016-09-07 as 10 10 49](https://cloud.githubusercontent.com/assets/32010/18313118/72eae6da-74e3-11e6-94b5-6558878d964b.png)

# Inbox
![captura de tela 2016-09-07 as 10 12 04](https://cloud.githubusercontent.com/assets/32010/18313148/9d8509d4-74e3-11e6-9e99-ee30ac0c29a0.png)

![captura de tela 2016-09-07 as 09 53 29](https://cloud.githubusercontent.com/assets/32010/18312689/5348a698-74e1-11e6-842c-7def809d73dd.png)

**Comment by mauricioabreu** [comment]
Thanks for opening the issue.

**Comment by mauricioabreu** [comment]
Pull request #153 addresses this problem. 

Thank you!

**Comment by luanfonceca** [comment]
I am closing this, as the pull request was already deployed.
o/

**Comment by joseluizcoe** [comment]
I did one test using my account and the sender name still "noreply" :(

Try:
- Go to: http://speakerfight.com/accounts/password/reset/
- Type your email
- Go to your gmail and:

![captura de tela de 2016-09-16 18 46 02](https://cloud.githubusercontent.com/assets/32010/18602220/fec5ae86-7c3d-11e6-8269-41e0a3e92074.png)

**Comment by mauricioabreu** [comment]
It is strange. Django docs say it is the right way to do this.
