### ISSUE TITLE
Fix deployment script

### ISSUE THREAD

**Issue by mauricioabreu** [luanfonceca/speakerfight#156]
@luanfonceca told me that the current deploy script is not working as expected.
In order to have a functional continuous integration/continuous delivery, we need to fix it.

**Comment by hdiogenes** [comment]
What's broken exactly? Any ideas on how can we try to fix it?

**Comment by mauricioabreu** [comment]
@luanfonceca I am very busy at my job and studying and using my spare time to it. So I am removing myself from this issue.

@hdiogenes the private key/public key handshake is not working. We need to generate a private key (server) and add it to the Travis server.
