### ISSUE TITLE
Improve I18n

### ISSUE THREAD

**Issue by renatooliveira** [luanfonceca/speakerfight#160]

**Comment by luanfonceca** [comment]
This is happen mailing in the Breadcrumb, i think that is just in there. But it is nice for someone look around.

**Comment by wagnerluis1982** [comment]
Sorry, but I didn't get. What tasks is involved in this issue?

**Comment by wagnerluis1982** [comment]
Hi, again I ask: what this issue is for?

**Comment by luanfonceca** [comment]
All the i18n problems and misspellings was already solved in other issues. So i am closing this one.
