### ISSUE TITLE
Enable SSL

### ISSUE THREAD

**Issue by luanfonceca** [luanfonceca/speakerfight#165]
In order for us to allow people to include the Schedule and in the future create a inline embedded proposal form we need to have SSL for sites who already runs on https to include our iframes.

**Comment by vmesel** [comment]
Why we dont use let's encrypt certificate?

**Comment by luanfonceca** [comment]
We should use Let's encrypt or Cloudflare.

**Comment by vmesel** [comment]
@luanfonceca how is the issue going? There is a thing called certbot that installs automaticaly an SSL certificate on Apache2/Nginx/whatever!

**Comment by luanfonceca** [comment]
Anyone get this issue yet, did you already used it? If you do and want to fix this i can give you access to the server and other stuffs.

**Comment by victor-torres** [comment]
I’m working on this issue.

**Comment by victor-torres** [comment]
DONE

- installed certbot (`~/certbot/`)
- generated certificates with certbot (auth via standalone server)
- apt-get update has been fixed (missing keys)
- nginx have been updated to version 1.6.2 (`apt-get update && apt-get -t wheenzy-backports install`)
- default site configured to use ssl certificates

TODO

- renew the certificates via crontab
- replace hardcoded http links (we may probably create another issue for this)

Note: there was another nginx installed with http_ssl_module installed but its version was too old (1.2.1)
