### ISSUE TITLE
Collapse long proposal design error

### ISSUE THREAD

**Issue by vmesel** [luanfonceca/speakerfight#167]
Hey folks,

I know that you have implemented the new design for the proposal, allowing big proposals to stay short. The problem is that it's not clear when the proposal is shortened or not, so I suggest you to do some signaling or anything like that letting the user know when the proposal he is reading is collapsed.

**Comment by vmesel** [comment]
Also, it should be nice if the user can collapse the big proposal again, so he keeps his page clean and steady!

**Comment by luanfonceca** [comment]
We can improve things forever, at least it is working, for me we have better issues to give our attention.

o/

**Comment by wagnerluis1982** [comment]
Hey, as it was me who designed the collapse proposal, I'm interested in solve that.

@vmesel, would be good to you after the collapsed proposals a "Show more" link is displayed?

**Comment by wagnerluis1982** [comment]
Hi, I'm thinking of something like this:

![image](https://cloud.githubusercontent.com/assets/428341/19389330/0321c15a-91fa-11e6-9aa9-47784fe3dfe1.png)

About a way to collapse again, I don't think is a good idea to have a "Hide text" link for each proposal, but some link or button in the top of page to collapse all.

**Comment by luanfonceca** [comment]
Dont add the hide, just the show button, and align it on center.

Em sex, 14 de out de 2016 10:39, Wagner Macedo <notifications@github.com>
escreveu:

**Comment by vmesel** [comment]
Why the user wont be able to retract the proposal he have read? This is nonsense man... If we have the show more button, we should have the opposite too!

**Comment by luanfonceca** [comment]
Keep it simple, I can found tons of UX patterns for collapses and in the
most the close is irrelevant and nobody uses it

Em sex, 14 de out de 2016 11:24, Vinicius Mesel <notifications@github.com>
escreveu:

**Comment by wagnerluis1982** [comment]
@vmesel, retracting is normally complicated because when the text is hidden you get lost in the page. 

To understand my point, go to Demo 8 on this page, http://www.aakashweb.com/demos/jquery-collapser/index.php#block-level, click "Show more", scroll down, click "Hide text" and see what happens: you don't go back to Demo 8 neither go to the next subject, that is Demo 9.

**Comment by wagnerluis1982** [comment]
Hi, I'm not really the frontend type, so I made a simple design to put the "Show more" link in the center.
It's highlighted along lines in the right and left to not mix with the content.

![image](https://cloud.githubusercontent.com/assets/428341/19405774/03c8fcf6-9252-11e6-9538-ea5ff0b1b771.png)

What do you think about?

**Comment by luanfonceca** [comment]
If it's working on small resolutions it's perfect

Em sex, 14 de out de 2016 21:10, Wagner Macedo <notifications@github.com>
escreveu:

**Comment by wagnerluis1982** [comment]
I got another situation: the proposals are collapsed only if height is greater than 150px, but I'm collapsing to exactly 150px.

I think would be a good idea to increase the collapsing threshold to 200px (or a bit less), maintaining css height to 150px. Or use the threshold of 150px but collapsing to 100px.

**Comment by wagnerluis1982** [comment]
Hi everybody.

The "Show more" design is done. What do you say of increasing the threshold which I said in the previous comment?
