### ISSUE TITLE
Requirements fail to install on Windows 10

### ISSUE THREAD

**Issue by samuelgrigolato** [luanfonceca/speakerfight#170]
I tried to build speakerfight on WIndows 10 (python 2.7.12), without success.

The error seems to be the same as reported here: [https://github.com/unbit/uwsgi/issues/547](url)

`uwsgi_os = os.uname()[0]`

> AttributeError: 'module' object has no attribute 'uname'

**Comment by luanfonceca** [comment]
You can comment the uwsgi line in the requirements.txt and try to install again

**Comment by samuelgrigolato** [comment]
It worked!

What did I lose for not being able to install uWSGI?

Anyway, I also needed to do a minor change to properly load the fixtures. `loaddata` wouldn't understand the forward slashes, breaking with an exception:

$ python manage.py loaddata deck/fixtures/user.json
> XXXXXX\venv\lib\site-packages\django\core\management\commands\loaddata.py:226: UserWarning: No fixture named 'deck/fixtures/user' found.

The solution was simple, changing the forward to backslashes was enough:

$ python manage.py loaddata deck\fixtures\user.json

What can we do to facilitate work for future Windows devs/deployers?

**Comment by luanfonceca** [comment]
@samuelgrigolato we fixed this in the master branch, if you pull the new code in master i think it is all working.

o/
