### ISSUE TITLE
pycparser version 2.15 causing compile error on package cryptography

### ISSUE THREAD

**Issue by phrfpeixoto** [luanfonceca/speakerfight#176]
As observed in issues #171 #165 current builds are breaking on TravisCI due to a compile error on package cryptography.

It's related to a bug in pycparser version  2.15.

background:
https://github.com/Kitware/candela/pull/452
https://github.com/pyca/cryptography/issues/3187

Opened Pull-Request #177

**Comment by luanfonceca** [comment]
Thanks @phrfpeixoto it was merged into master branch

o/
