### ISSUE TITLE
Usernames cannot contain spaces nor special characters

### ISSUE THREAD

**Issue by victor-torres** [luanfonceca/speakerfight#208]
A specific account with space in her username was breaking the reverse search regex and pages like the Caipyra 2017 weren't loading properly. I logged into the server and replaced the space in the username by an underscore. We still have to validate the username before saving to the database.

**Comment by luanfonceca** [comment]
Fixed on commit b59f21ee28cc8eaf56cbc49fd7926e243e92276f
