### ISSUE TITLE
Set Profile Photo

### ISSUE THREAD

**Issue by Ryllari** [luanfonceca/speakerfight#210]
Currently, the user can not change their profile photo. Create a function so the user can set their profile photo.

**Comment by luanfonceca** [comment]
Hi @Ryllari, we use the Gravatar to get the picture, by using it we do not have to concern on storing the user pictures, which seemed to be easier for me to at least have photos haha

But if you want to make this feature i will help on every step of the process of coding and testing o/

**Comment by alessandroHenrique** [comment]
@luanfonceca I'm gonna take this issue.

**Comment by luanfonceca** [comment]
According to the PR #216 we have allowed a first version of this feature.

![](http://g.recordit.co/Mg7iGWx4sR.gif)
