### ISSUE TITLE
Remove past events from main even list and create "past events" section

### ISSUE THREAD

**Issue by biancarosa** [luanfonceca/speakerfight#211]

**Comment by luanfonceca** [comment]
Hi @biancarosa, the PR #135 should fix that when its done.

o/

**Comment by luanfonceca** [comment]
About the Past Events page #217 i created a issue for that.

You you want to contribute more please feel free to open and close our issues.

**Comment by mauricioabreu** [comment]
Can this issue be closed? @luanfonceca

**Comment by luanfonceca** [comment]
I am closing this one, cause that was already fixed on other PR.
