### ISSUE TITLE
Add login button on the header of the main page

### ISSUE THREAD

**Issue by biancarosa** [luanfonceca/speakerfight#212]
For a user that already knows the website, the process of clicking into a button to reach the login page makes the user lose a lot of time.

**Comment by luanfonceca** [comment]
Hi @biancarosa i am closing this issue, cause @alessandroHenrique just implemented a issue to add the Login button on the home page.

![screen shot 2017-08-11 at 18 27 41](https://user-images.githubusercontent.com/1490875/29232628-02b8727a-7ec3-11e7-90be-698ebe80f811.png)
