### ISSUE TITLE
Generate certificate and install HTTPS support for login page

### ISSUE THREAD

**Issue by apast** [luanfonceca/speakerfight#214]
Generate SSL certificate using free tools like letsencrypt and install it on main server.

**Comment by luanfonceca** [comment]
I think that we already have one, but let us confirm that.

@victor-torres did you make that a long time ago in the speakerfightm, right?

**Comment by apast** [comment]
It is installed!

But, can it is not redirecting automatically on login screen.

Can we setup this on server?

**Comment by victor-torres** [comment]
Yes, it's, @luanfonceca. You may rename the ticket to "Automatically redirect users from port 80 to 443 on nginx".

**Comment by victor-torres** [comment]
And BTW, it's already done, @luanfonceca and @apast.

**Comment by apast** [comment]
Thanks, @victor-torres! It working perfectly!!
