### ISSUE TITLE
Users created without the social login doesn't has first_name and last_name

### ISSUE THREAD

**Issue by luanfonceca** [luanfonceca/speakerfight#24]
The Form of Signup, in the `/accounts/signup/` do not ask the `first_name` and `last_name`, for now we are just going to use the `@{{ username }}` for that.

**Comment by viniciusban** [comment]
I signed up without social login and my username is been shown, instead of my first and last name.

Example: http://speakerfight.com/events/pythonbrasil11/#round-1-fight

**Comment by luanfonceca** [comment]
Hi @viniciusban, we have a lots of drawbacks using the signup by email, the names, contact info, avatar... And We do not have plains for built a profile interface for now.

The truth is that we are more likely in removing it and keep just the Github, Google and Facebook auth.

**Comment by viniciusban** [comment]
OK.

Would it be possible to migrate my account to a new one, created with Github or Google?

How would this procedure be?

**Comment by luanfonceca** [comment]
If you already created a proposal, event or vote in anything. For now, you need to create a new account using Github, for instance, and send me an [email](mailto:luanfonceca@gmail.com) with your username on Github and I will migrate it.

If you never did anything and the email from your Speakerfight account is different from the Github, just start using with your Github and abandon your old account.

If the email is the same (because the email is unique) I can delete your account for you create a new one.
