### ISSUE TITLE
Responsive Navbar bugs

### ISSUE THREAD

**Issue by luanfonceca** [luanfonceca/speakerfight#266]
If we open Speakerfight using small screen we face several bugs with the navbar and sidebar:

1. Login navbar not closes when we click for the second time;
1. Sidebar are not overlapping the rest of the site;
1. Sidebar doesn't work on the index site

![screen shot 2017-09-28 at 17 47 12](https://user-images.githubusercontent.com/1490875/30989743-23eb3cde-a475-11e7-88b3-135b35dd46e3.png)

**Comment by sneakycr0w** [comment]
It looks like you've got a large project tree. Do you have a permalink to your CSS?

**Comment by luanfonceca** [comment]
Hi @sneakycr0w, Yeah, the project is running since 2014. If you need anything, just tell me here.
