### ISSUE TITLE
Responsive Call To Action button bugs

### ISSUE THREAD

**Issue by luanfonceca** [luanfonceca/speakerfight#267]
Beside its size is too exaggerate for the layout, if the text breaks to a new line the button doesn't follow it. So it should be nice if we change his layout to a simple one that works better in small screens.

![screen shot 2017-09-28 at 17 52 02](https://user-images.githubusercontent.com/1490875/30989908-c9ed893e-a475-11e7-98e1-ee1f900da7c2.png)

**Comment by elina-codes** [comment]
I'd be happy to pick this up!

**Comment by luanfonceca** [comment]
Hi @elina-codes, Okay! If you need anything from me, please, just tell me.

<3

**Comment by elina-codes** [comment]
Awesome! Will do. :)

**Comment by elina-codes** [comment]
Oh, would you mind assigning the issue to me?

**Comment by luanfonceca** [comment]
Done, you should receive a invite in your mail about it, after accepting i will be able to asign you in the issue.

**Comment by elina-codes** [comment]
@luanfonceca something came up this morning that means I won't have the time I thought I'd have to work on this. I'm afraid you'll have to assign it to someone else :(. So sorry - best of luck!

**Comment by luanfonceca** [comment]
:(

Okay @elina-codes, if you think that you have at least time to implement this on the Event Detail page, its enough for me.

Thanks for everything <3

**Comment by elina-codes** [comment]
I'll let you know if anything changes, or if I see that this is still open once later on I'll message you!

**Comment by luanfonceca** [comment]
Okay @elina-codes, there are many ways to contribute with Speakerfight and i am here to help you out on all one them

o/

**Comment by lex111** [comment]
@luanfonceca I understand correctly, do I need to change the size of buttons for mobile devices? Like that:

![image](https://user-images.githubusercontent.com/4408379/31038851-a67a47be-a581-11e7-96c0-55e9886fce32.png)

**Comment by luanfonceca** [comment]
Hi @lex111, yeah. Fix this bugs with small screens.

**Comment by lex111** [comment]
@luanfonceca ok I want to take it.

**Comment by luanfonceca** [comment]
Ok @lex111!

**Comment by lex111** [comment]
Created PR #278
