### ISSUE TITLE
Remove Organization

### ISSUE THREAD

**Issue by luanfonceca** [luanfonceca/speakerfight#287]
Allow users to delete the Organization.

![screen shot 2017-10-03 at 19 16 22](https://user-images.githubusercontent.com/1490875/31151776-778bb406-a86f-11e7-893b-46f56678deee.png)

**Comment by arturfelipe** [comment]
Hi @luanfonceca can I get this one?

**Comment by arturfelipe** [comment]
@luanfonceca What do you think to change the URL to: `/organizations/<slug:slug>/delete/`? I think I will need it to get the expected organization to be deleted by slug right?

**Comment by luanfonceca** [comment]
You are right, @arturfelipe. Thats my mistake on designing it

**Comment by luanfonceca** [comment]
This was done on PR #298.
