### ISSUE TITLE
Improve the Profile page.

### ISSUE THREAD

**Issue by luanfonceca** [luanfonceca/speakerfight#319]
This issue belongs to @nicysneiros.

Improvements:
- Form layout
- Twitter

**Comment by girol** [comment]
Can you help me where the files are located?

Which improvements do you need? :)

**Comment by luanfonceca** [comment]
This issue is assigned to @nicysneiros @girol

**Comment by meiralins** [comment]
@nicysneiros @luanfonceca ,
yesterday I sent #310 that is related to this issue.
remember to hide the Change Photo button if user is not in its own profile.

**Comment by luanfonceca** [comment]
@meiralins i will merge both, okay?

**Comment by meiralins** [comment]
@luanfonceca okay!
but if it is easier to @nicysneiros and you, feel free to reject it =)

**Comment by meiralins** [comment]
either way, i will do a quick rebase now.

**Comment by luanfonceca** [comment]
This was done on the PR #327
