### ISSUE TITLE
Add first_name and last_name on the Sign Up form.

### ISSUE THREAD

**Issue by luanfonceca** [luanfonceca/speakerfight#324]
This issue belongs to @maribedran.

The files that you may need to change the `core/templates/account/signup.html` and the SignupForm class.

Reference: https://stackoverflow.com/a/35029585/1530565

**Comment by RajatGarg97** [comment]
May I try this @luanfonceca ?

**Comment by luanfonceca** [comment]
Hi @RajatGarg97, sorry but this issue is intended to be develop by @maribedran.

**Comment by luanfonceca** [comment]
This was done on PR #329.
