### ISSUE TITLE
"JOIN THE FIGHTERS" button at bottom of homepage leads to 400

### ISSUE THREAD

**Issue by jChapman** [luanfonceca/speakerfight#333]
Clicking on the button at the bottom of the page leads me to this link:
https://speakerfight.com/events/'%20%%7D
Which yields a 400 Bad Request

**Comment by luanfonceca** [comment]
Hi @jChapman, do you want to fix that?

Looks like its just a html or translation problem.

**Comment by luanfonceca** [comment]
This was done on PR #335
