### ISSUE TITLE
Users cannot save the Description from Activity Modal.

### ISSUE THREAD

**Issue by luanfonceca** [luanfonceca/speakerfight#342]
In the Create Scheduled page, there are a bug that doesn't save Activity's Description.

![](http://g.recordit.co/Hx5u3XCeSZ.gif)

**Comment by cleisonsilfer** [comment]
I think I can help with this bug.

**Comment by luanfonceca** [comment]
Okay @cleisonsilfer, this page uses a bit of Ajax with an api built on `django-rest-framework` okay?

**Comment by ryanermita** [comment]
@luanfonceca i will look into it to. :)
