### ISSUE TITLE
Allow user to change the `activity_type` on Updating the Activity

### ISSUE THREAD

**Issue by luanfonceca** [luanfonceca/speakerfight#343]
We need to allow users to choose the actitivty on the Creation and Update forms.

The create actitivty form:
<img width="958" alt="screen shot 2017-10-17 at 18 25 53" src="https://user-images.githubusercontent.com/1490875/31690276-a30167a8-b368-11e7-9a34-99a5d5ab6cb9.png">

The update actitivty form:
<img width="989" alt="screen shot 2017-10-17 at 18 26 22" src="https://user-images.githubusercontent.com/1490875/31690298-b1de5c86-b368-11e7-93fb-71c40c88d533.png">

**Comment by ryanermita** [comment]
@luanfonceca i'll take this one.

**Comment by ryanermita** [comment]
@luanfonceca where can i add the activity? is it in the user side or admin side?

**Comment by luanfonceca** [comment]
Hi @ryanermita, we dont use the Admin. Follow this workflow:

1. Create an Event
2. Click on `Create Schedule` button
3. Click on `Add Activity` button

**Comment by ryanermita** [comment]
thanks @luanfonceca , im looking into it.
