### ISSUE TITLE
Some pages are borderless

### ISSUE THREAD

**Issue by cleisonsilfer** [luanfonceca/speakerfight#347]
Some pages have a problem that lacks a margin between the top bar and the content.
<img width="1280" alt="screen shot 2017-10-18 at 12 21 57" src="https://user-images.githubusercontent.com/11786543/31772423-5d453dbe-b4be-11e7-9ebd-71ea800a5b75.png">
<img width="1280" alt="screen shot 2017-10-18 at 12 21 45" src="https://user-images.githubusercontent.com/11786543/31772424-5d6ed5ac-b4be-11e7-9b1a-abcc522607d4.png">

**Comment by cleisonsilfer** [comment]
Fixed in PR #348

**Comment by luanfonceca** [comment]
Thanks @cleisonsilfer!
