### ISSUE TITLE
SSL certificate maybe is expired

### ISSUE THREAD

**Issue by berinhard** [luanfonceca/speakerfight#366]
I tried to access https://speakerfight.com/ and I'm receiving security warnings both in Google Chrome and in Firefox.

![screenshot from 2017-10-31 13-18-55](https://user-images.githubusercontent.com/238223/32232026-3ab47a4c-be3e-11e7-98c0-9ceb7e84a9c5.png)

**Comment by berinhard** [comment]
@luanfonceca since this is a deploy thing, I don't know if I should have reported it here.

**Comment by luanfonceca** [comment]
Its okay to add a issue here. i just have renewed the ssl certificate and everything else.

<3
