### ISSUE TITLE
Remove the `publish` flag.

### ISSUE THREAD

**Issue by luanfonceca** [luanfonceca/speakerfight#37]
In Proposals and Events, the `publish` flag is practically not used for anyone.
So or we remove him or just the to `publish = True`.

**Comment by raphapassini** [comment]
@luanfonceca,

I think the best aproach is just set de ```default``` to ```True```, do you agree? If so i'll take this one! :)

**Comment by luanfonceca** [comment]
Hi @raphapassini, i agree with you, my only concern is that we do not have any feedback for the author that his proposal is still not published.

But yes, the default `True` is good enough for that. 

o/

**Comment by cacarrara** [comment]
If https://github.com/luanfonceca/speakerfight/pull/55 be approved we can close this.

**Comment by luanfonceca** [comment]
This issue are being closed together with the PR: #55
