### ISSUE TITLE
Update README.md or create CONTRIBUTING.md with how contribute instructions

### ISSUE THREAD

**Issue by ewertonorg** [luanfonceca/speakerfight#41]
My suggestion is that the process to contribute should be detailed on the readme/contributing.
Something like this:
[CONTRIBUTING.md](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md)

**Comment by luanfonceca** [comment]
We are need this so mucj high now, can you get back to this @ewertonorg?

We can discuss here what should and should not enter in this file.
