### ISSUE TITLE
Redesign the index page

### ISSUE THREAD

**Issue by luanfonceca** [luanfonceca/speakerfight#47]
I built the index page in some few second... So it would be nice if we get some time and rebuild it. Showing small features and the latest events, some links to share the Speakerfight on facebook.

Just that already is more than good.

**Comment by lucasmiqueias** [comment]
I Will try redesign

**Comment by jonatasoliveira** [comment]
@lucasmiqueias, I did a small redesign of index. If you have any suggestions please let me know.

**Comment by lucasmiqueias** [comment]
Nice, i will create the ux.
