### ISSUE TITLE
Speaker Photo on proposals

### ISSUE THREAD

**Issue by humrochagf** [luanfonceca/speakerfight#53]
Add the speaker photo from its linked social profile on the proposal description

**Comment by jonatasoliveira** [comment]
One of the easiest way to get a profile picture is using gravatar. Here is an example code:

```
>>> import hashlib
>>> hashlib.md5('email@gmail.com').hexdigest()
'1919bfc4fa95c7f6b231e583da677a17'
```

Add the hash to the gravatar URL like this:
http://www.gravatar.com/avatar/1919bfc4fa95c7f6b231e583da677a17

**Comment by luanfonceca** [comment]
We already have that by using the `django-allauth`, of course this just work on people who have logged in using it.

```python
In [2]: User.objects.filter(socialaccount__isnull=False).first()
Out[2]: <User: luanfonceca>

In [3]: u = User.objects.filter(socialaccount__isnull=False).first()

In [4]: u.socialaccount_set.first().get_avatar_url()
Out[4]: u'https://avatars.githubusercontent.com/u/1490875?v=3'
```

**Comment by humrochagf** [comment]
i wrote one using @luanfonceca idea, and @jonatasoliveira as a fallback
