### ISSUE TITLE
SSL Certified Expired

### ISSUE THREAD

**Issue by rafapg** [luanfonceca/speakerfight#557]
The website is running with a expired certified:
![image](https://user-images.githubusercontent.com/6156406/47857272-fb59d900-ddc7-11e8-9f3e-997e8931c2b2.png)

**Comment by JPTIZ** [comment]
Up.

Is there a way we can help with this issue? It's sort of inconvenient that the browser keeps telling we're in an insecure domain.

**Comment by luanfonceca** [comment]
Hello @JPTIZ i did the setup on the auto-renew of those certificates but for some reason it didn't worked.

I just renew it by hand and later i'll look on it, we are using the Let's encrypt so it should be something easy to fix, thanks :D
