### ISSUE TITLE
Proposals should be separeted in 'voted' and 'not voted' to ease the voting process.

### ISSUE THREAD

**Issue by hmln** [luanfonceca/speakerfight#59]
The current ordering is alphabetical and doesn't care about voted or non voted by the user. IMO, it would be better to show non voted proposals first or in a separate section.

Maybe a new screen showing only unvoted talks would be more helpful. Thoughts?

**Comment by luanfonceca** [comment]
Hi @hmln, the vote page needs a lots of improvements in his UI, we are about to add a new feature for not reloading the page in each vote we made. So we are working on this and of course we can rethink the way that the proposals are showed!

If we just order the proposals by the not voted first and by name, we will make a huge improvement on it, do you can take this?

**Comment by hmln** [comment]
@luanfonceca , sure.

**Comment by luanfonceca** [comment]
Nice! 
We have a chat on [gitter.im](http://gitter.im/luanfonceca/speakerfight), if you want come to talk. 

o/
