### ISSUE TITLE
Email feedback after sign up

### ISSUE THREAD

**Issue by berinhard** [luanfonceca/speakerfight#65]
It would be nice to send an email to the user welcoming after him/her sign up.

**Comment by felipevolpone** [comment]
@luanfonceca I implemented it. I canno't test it so well 'cause settings.py doesn't have all email configurations like EMAIL_HOST, EMAIL_PORT, etc. Btw, If something is wrong please tell me.

**Comment by felipevolpone** [comment]
You can check it in this PR https://github.com/luanfonceca/speakerfight/pull/82

**Comment by luanfonceca** [comment]
Closing this issues according the PR #83.
