### ISSUE TITLE
Prepare settings for different environments

### ISSUE THREAD

**Issue by berinhard** [luanfonceca/speakerfight#66]
Now we have only one settings file and this is a problem when we need more custom configuration depending on the environment, for example, the database or the email backends. We need to split it into differents settings for differents environments **or** make it more extensible. Maybe we could use @henriquebastos [project](https://github.com/henriquebastos/django-decouple) for decoupling it.

**Comment by henriquebastos** [comment]
[django-decouple](https://github.com/henriquebastos/django-decouple) was deprecated. Use [python-decouple](https://github.com/henriquebastos/python-decouple) which will solve the configuration decoupling problem in any python project you may have.

I went through speakerfight's settings and using python-decouple should be simple.

**Comment by rougeth** [comment]
+1 to python-decouple and I can do it (:

**Comment by humrochagf** [comment]
to use python-decouple i suggest use [dj-database-url](https://github.com/kennethreitz/dj-database-url) to use a single variable on .env file

**Comment by nielsonsantana** [comment]
+1 for python-decouple

**Comment by luanfonceca** [comment]
With the issue #239, we will use `python-decouple`, finally.

<3
