### ISSUE TITLE
404 after ask to reset e-mail at "reset done"

### ISSUE THREAD

**Issue by cadu-leite** [luanfonceca/speakerfight#67]
After post e-mail address to reset password ..
the user is redirect to the follow URL:

    http://speakerfight.com/accounts/password/reset/done/

that has a link named "sign up". When click on "signup" link in the above URL, 
the browser try to load the following URL...

    http://speakerfight.com/accounts/password/reset/done/signup.html

and this URL returns a 404 page.

**Comment by cadu-leite** [comment]
the same happens after post the reset password form, and clicked the sign up link 
the follow URL returns a 404 page

    http://speakerfight.com/accounts/password/reset/key/done/signup.html

**Comment by luanfonceca** [comment]
Hi @cadu-leite, thanks for noticing, the problem was caused by a link url, i just fix it!

This part of authentication is just a copy-and-paste from the `django-allauth`, that's why it is so ugly and full of this little bugs.

Thanks for all.

**Comment by cadu-leite** [comment]
u r Welcome. 
its just a litle peace and one could live with that.  we are devs anyway !
congrats by the app. well done
