### ISSUE TITLE
message not visible on password reset form

### ISSUE THREAD

**Issue by cadu-leite** [luanfonceca/speakerfight#69]
I made a mistake when writen my e-mail address on reset password form ... 
and there was a error message, but I didint saw at the first moment. 

may its a problem with me, but may be should be nice to paint it red and put it on bold. 8P

**Comment by hmln** [comment]
Sorry for the duplicated references. I didn't know github would do that automagically.

**Comment by luanfonceca** [comment]
I didnt know that too, but this is not a problem, i actually like it, because it shows that you are doing something related to this, in a bigger project it can become a mess, but for our case its a good thing in think 

o/

o/

**Comment by luanfonceca** [comment]
@hmln how it is going the PR for this issue?

o/

**Comment by mauricioabreu** [comment]
It is still hard to see if something went wrong.
I suggest to add a message telling the user what went wrong.

**Comment by pgrangeiro** [comment]
Hi guys! I've submitted PR #193 to fix this issue

**Comment by pgrangeiro** [comment]
Hi guys! I've opened a new PR #194 following #193 recomendations.

**Comment by mauricioabreu** [comment]
Closed via #194
