### ISSUE TITLE
Some general Statistics along the event details

### ISSUE THREAD

**Issue by cadu-leite** [luanfonceca/speakerfight#70]
What about show some statistics 
ex.:

NUM of Proposals 
Num of speakerd (may differ if a speaker send more than 1 ) 
Num of votes (total)

**Comment by luanfonceca** [comment]
Hi @cadu-leite we can just summarize that data and show it on the "*Event List page*", in the "*Event Detail page*" and in the future add a more verbose information to be showed on the "*Event Feedback page*", according to the issue #60.

For now this can be an MVP version of the *Event Feedback page*, what did you think of it?!

And thanks for the feedback!

**Comment by luanfonceca** [comment]
This solves? I am showing this just to the Author of the event, I think if it was public can discourage the new users to add proposals.

![screen shot 2015-06-16 at 9 04 34 pm](https://cloud.githubusercontent.com/assets/1490875/8197230/88e16736-146b-11e5-98f2-00f83acc700a.png)

**Comment by cadu-leite** [comment]
may you are right

Em ter, 16 de jun de 2015 21:07, Luan Fonseca de Farias <
notifications@github.com> escreveu:
