### ISSUE TITLE
Acesso a conta 

### ISSUE THREAD

**Issue by HigorMonteiro** [luanfonceca/speakerfight#71]
estou com dificuldades na hora de logar com linha conta não da certo nem com gmail que foi que eu me cadastrei e nem com a conta do github , como posso rever minha conta ?
ja refiz minha senha inumaras vezes .

**Comment by luanfonceca** [comment]
Qual tipo de dificuldade? Aparece algum erro na página, uma mensagem
estranha, é em algum momento específico do login?
Preciso de mais informações pra poder te ajudar o/

Entra no nosso chat depois: http://gitter.im/luanfonceca/speakerfight

Em ter, 16 de jun de 2015 10:54 PM, HigorMonteiro <notifications@github.com>
escreveu:

**Comment by HigorMonteiro** [comment]
Bom dia luan Fonseca!

Não consigo logar com minha conta do gmail para tipo acompanhar minha
proposta de palestra vc poderia me ajudar ?

Em quarta-feira, 17 de junho de 2015, Luan Fonseca de Farias <
notifications@github.com> escreveu:

**Comment by luanfonceca** [comment]
Fala @HigorMonteiro, como te falei preciso de mais detalhes. o/

Apareceu alguma mensagem de erro, algo como:  "Essa conta social está conectada a um outro registro de usuário.", "Você já tem uma conta, mas escolheu o provedor errado para acessar desta vez."?

Preciso desse tipo de detalhes para reproduzir o teu problema e então resolve-lo. Porém o que eu acho que pode ter acontecido é: Você tentou se criar uma conta e deu algum problema, porém a a conta foi criada mesmo assim, na próxima vez você tentou utilizar uma rede social com o mesmo email de uma conta que ja existe... Por isso eu estou pedindo um print ou alguma informação melhor pra poder te ajudar.

**Comment by HigorMonteiro** [comment]
iNFORMA QUE LOGIN OU SENHA NÃO CONFERE
LOGIN : higor.tecinfor@gmail.com


Em 23 de junho de 2015 13:31, Luan Fonseca de Farias <
notifications@github.com> escreveu:

**Comment by luanfonceca** [comment]
Fala @HigorMonteiro, consegui reproduzir o teu problema e então resolvê-lo, solicitei pela interface um reset da tua senha, redefine ela e tenta novamente que já ta tudo ok!

Valeu.

**Comment by HigorMonteiro** [comment]
ok valeu vou olhar aqui .

Em 9 de julho de 2015 20:17, Luan Fonseca de Farias <
notifications@github.com> escreveu:
