### ISSUE TITLE
Add more info in the CSV

### ISSUE THREAD

**Issue by luanfonceca** [luanfonceca/speakerfight#73]
For now we just have: ID, Title, Author and Votes, would be nice if we can add more information like: 
- How many Votes (For now we have a Sum of all votes), 
- The author email (We use the login)

And we need to sort the Proposals by the most voted first.

**Comment by cadu-leite** [comment]
WOW! what a masss !
well, finally there is a clean, and i hope a nice pull request for this one at 
 
https://github.com/luanfonceca/speakerfight/pull/76
