### ISSUE TITLE
Allow the user to choose which idiom he want.

### ISSUE THREAD

**Issue by luanfonceca** [luanfonceca/speakerfight#9]
Changing in the `Session` and who knows at the user's table too.

**Comment by vmesel** [comment]
I think this issue is already solved, right @luanfonceca ?

**Comment by luanfonceca** [comment]
Nope, we should have something in the User dropdown to change his language.

**Comment by wagnerluis1982** [comment]
Currently, the language is globally defined on `settings.py`, right?

How about to also make this automatically, by reading the Accept header of request? The user settings would still be the first place to see, but if wasn't set, the request info would be considered.

**Comment by mauricioabreu** [comment]
@wagnerluis1982 hmmm, it seems a bit complicated to solve the problem.
The feature does not payt the code and your efforts developing it. Also reading headers is not a good idea. Every browser does in its own way. What do you think?

**Comment by wagnerluis1982** [comment]
@mauricioabreu what exactly is complicated? The user-defined idiom is what this issue is for. So in the main view (read by all pages) we would have something like:

```
idiom = user.get_idiom() or get_request_idiom(request)
```

**Comment by mauricioabreu** [comment]
@wagnerluis1982 parsing headers and trust them. I think that having the language avaible in the user settings is good enough. I am not against the idea but not sure if the efforts making this code will pay the feature.

**Comment by wagnerluis1982** [comment]
@mauricioabreu, I'm not really an expert in i18n, but I remembered that Django has a standard way to discover the language by request. And I found that is LocaleMiddleware.

The following link explains how this middleware works. According to what I read, it's only a matter of adding to `MIDDLEWARE_CLASSES` to work!

https://docs.djangoproject.com/en/1.7/topics/i18n/translation/#how-django-discovers-language-preference

Of course this will not completely solve the problem, as the user can't override the browser idiom, but is a starting point.

**Comment by mauricioabreu** [comment]
@wagnerluis1982  now we are talking :P

The middleware can make it work. Cool!

**Comment by wagnerluis1982** [comment]
@mauricioabreu great!

So, anyone working in this issue?  If not, I'm assigning myself.

**Comment by mauricioabreu** [comment]
@wagnerluis1982 not that I remember.
You are the best person to workn on this issue so... go ahead! :-)

If you need anything don't forget to ask here.

**Comment by phrfpeixoto** [comment]
@wagnerluis1982 Are you working on this?

**Comment by wagnerluis1982** [comment]
@phrfpeixoto yes, man!

I'm still planning things, but I'll have some code soon!

**Comment by phrfpeixoto** [comment]
I think that make this a setting in the user model is a bit like an overkill. You simply use session and cookie approaches builtin in django. You can also use browser's local storage.

**Comment by wagnerluis1982** [comment]
Hmmm, we have to see what the others think!

In general I think you are right, but this hurts the user experience since the user needs to change the idiom every time he uses another computer or browser. Users that don't store cookies will not like it too.

Maybe there is a way to make this happens without performance problems.

**Comment by wagnerluis1982** [comment]
One suggestion.

1. We try to use the language information from the Session/Cookies
2. If not found we get the information from the database

To reduce the impact to performance, when the user changes the idiom, all his sessions, but the current one, will be closed. This makes that we don't have inconsistency of idioms among sessions.

Of course the user can set the idiom to be automatic, by the browser settings.

**Comment by wagnerluis1982** [comment]
Hi, in the #188 I added the `LocaleMiddleware` to get info from Accept-Language request header.

Although this middleware try to find the language info in the session, it doesn't write anything to the session so the next time this is done.

So I need to make a subclass of LocaleMiddleware to make that happens, where is the best place to put this class?

**Comment by wagnerluis1982** [comment]
Hi, to allow the user change his idiom I made the following design. Please, say what you think.

1\. The current idiom is showed next to user dropdown.

![image](https://cloud.githubusercontent.com/assets/428341/20045989/5541cdd0-a484-11e6-8f0f-75123c237aae.png)

2\. We can change the language by clicking in the current idiom dropdown.

![image](https://cloud.githubusercontent.com/assets/428341/20045882/5758293a-a483-11e6-85c0-1fe68d622289.png)

3\. And the idiom is changed :smile: 

![image](https://cloud.githubusercontent.com/assets/428341/20045962/1880270c-a484-11e6-8be0-0917289ddd33.png)

**Comment by abispo** [comment]
I agree with this approach.

**Comment by luanfonceca** [comment]
@wagnerluis1982 how is going that? Can you push some code to a PR?
