### ISSUE TITLE
See my talks

### ISSUE THREAD

**Issue by tarsisazevedo** [luanfonceca/speakerfight#90]
I want a page to see the all talks I submit.

**Comment by mauricioabreu** [comment]
@luanfonceca @tarsisazevedo Should this page show how many votes all user talks have?
Currently there is no way to see this information, is there?

**Comment by luanfonceca** [comment]
If we show how many votes this can influence the user to abandon the event
or something like, but normally the events processes doesn't use just the
votes for choose the talks... I didn't think it is good to show, just the
proposal with the action block and when it is clicked we can redirect to
the event detail page with the proposal anchored in the url.

o/

Em qui, 20 de ago de 2015 11:30 AM, Mauricio de Abreu Antunes <
notifications@github.com> escreveu:

**Comment by mauricioabreu** [comment]
But votes would be just visible for authors, co-authors and jury. Is not that a good thing?

**Comment by luanfonceca** [comment]
They are visible for they, this page is only for the user it self, the
author of the event will not see this page.

Em qui, 20 de ago de 2015 1:54 PM, Mauricio de Abreu Antunes <
notifications@github.com> escreveu:

**Comment by tarsisazevedo** [comment]
I agreed with @luanfonceca, this page just show talks. Votes are to event's owner.

**Comment by luanfonceca** [comment]
Done in the #99 PR.
