### ISSUE TITLE
Change vote

### ISSUE THREAD

**Issue by tarsisazevedo** [luanfonceca/speakerfight#91]
I want to change vote I gave to a talk.

**Comment by mauricioabreu** [comment]
Thank your for opening this issue.

To make this work, I think all rating images (laughing, happy, angry, etc) should appear in the screen at the same time. The one you voted for should have no transparency (like when you move your mouse over the faces).

What is your opinion? What about yours @luanfonceca ?

**Comment by luanfonceca** [comment]
We can add a `opacity: 0.4` maybe this can be enough.

 o/

**Comment by mauricioabreu** [comment]
Ok, agreed.

**Comment by wagnerluis1982** [comment]
This issue is already assigned to someone?

**Comment by mauricioabreu** [comment]
@wagnerluis1982 nope

I can help you to make it happen since I have a good knowledge of the codebase. :)

**Comment by wagnerluis1982** [comment]
@mauricioabreu
I, on contrary, don't know anything about the codebase.

I will give a try. Where I need to touch to make this happens?

**Comment by darknessHO** [comment]
@wagnerluis1982 Do you still want to do it?.

**Comment by wagnerluis1982** [comment]
Yes, but I can't do it soon. Feel free to assign to yourself.

**Comment by wagnerluis1982** [comment]
Hi, anyone is working on this? If not, I will start to work.

But I have some questions:

1. What models are involved when someone votes?
2. Is it needed to keep log of previous vote options for a proposal?
3. There will be an expire time to change vote?

**Comment by luanfonceca** [comment]
Hey @wagnerluis1982 

1) I think just the Vote, in this models we have a `rate` field, you just need to change it.
2) Nope, just change
3) You can just use the same that is used in the `RateProposal` view.

For the UI i would something like:
All the rates are shown with a `opacity: 0.6`, when i choose one it is saved (as it is today using ajax) the rest of the rates will be affected by css rule `opacity: 0.6` and the selected one is marked as `opacity: 1`.

Initial state:
![screen shot 2016-10-13 at 11 43 24 am](https://cloud.githubusercontent.com/assets/1490875/19353606/483d4c3e-913a-11e6-9975-679fbf471b0c.png)

I choose one:
![screen shot 2016-10-13 at 11 43 55 am](https://cloud.githubusercontent.com/assets/1490875/19353622/57ec26c8-913a-11e6-8e96-e9e26f45f064.png)

I choose other rate to change my vote:
![screen shot 2016-10-13 at 11 44 16 am](https://cloud.githubusercontent.com/assets/1490875/19353649/6730817e-913a-11e6-9a88-0fbe28ff7249.png)

Then i change it:
![screen shot 2016-10-13 at 11 45 07 am](https://cloud.githubusercontent.com/assets/1490875/19353672/850d088e-913a-11e6-851c-ce08dae57ce7.png)


Maybe we should change the opacity from 0.6 to 0.4, and I can help you on this part if you need o/

**Comment by wagnerluis1982** [comment]
@luanfonceca:

I understood. Now, get to work :smile:
And yes, the opacity should be 0.4 (or less).

**Comment by wagnerluis1982** [comment]
Hey @luanfonceca 

If I change the opacity from 0.6 to 0.4 on `.flat-icon` class, that means to change for all other flat-icons, (even that as I could see are still not be used), right?

**Comment by luanfonceca** [comment]
This was done in the PR #186.
